MANDATORY_FIELD_ERROR_MESSAGE = 'This field is required.'
INVALID_USER_ERROR_MESSAGE = "Invalid user id or user doesn't exist."
INVALID_TOKEN_ERROR_MESSAGE = "Invalid token for given user."
INVALID_EMAIL_ERROR_MESSAGE = 'Enter a valid email address.'
INVALID_USERNAME = 'Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.'
INVALID_CREDENTIALS_ERROR_MESSAGE = 'No active account found with the given credentials'
EXPIRED_TOKEN_ERROR_MESSAGE = 'Token is invalid or expired'
USERNAME_ALREADY_TAKEN_ERROR_MESSAGE = 'A user with that username already exists.'
EMAIL_ALREADY_TAKEN_ERROR_MESSAGE = 'user with this email already exists.'
PASSWORD_TOO_SHORT_ERROR_MESSAGE = 'This password is too short. It must contain at least 8 characters.'
PASSWORD_TOO_CLOSE_USERNAME_ERROR_MESSAGE = 'The password is too similar to the username.'
TOO_COMMON_PASSWORD_ERROR_MESSAGE = 'This password is too common.'
NO_PERMISSION_ERROR_MESSAGE = 'You do not have permission to perform this action.'
AUTHENTICATION_MISSING = "Authentication credentials were not provided."
