# Generated by Django 6.0.2 on 2026-02-09 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeadlyBurger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MenuTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('TR', 'Troll'), ('CL', 'Classique')], default='CL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Nuggets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Nuggets',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('NU', 'Nuggets'), ('SP', 'Sel ou Poivre'), ('ME', 'Menu'), ('AD', 'Addition'), ('DB', 'Burger de la Mort')], max_length=2)),
                ('explanations', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SaltOrPepper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_as_menu_1', to='quiz.menutheme')),
                ('menu_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_as_menu_2', to='quiz.menutheme')),
                ('menu_troll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_as_menu_troll', to='quiz.menutheme')),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='NuggetQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('nuggets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.nuggets')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('nuggets', 'question')},
            },
        ),
        migrations.AddField(
            model_name='nuggets',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='nuggets_questions', through='quiz.NuggetQuestion', to='quiz.question'),
        ),
        migrations.CreateModel(
            name='MenuThemeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.menutheme')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('menu_theme', 'question')},
            },
        ),
        migrations.AddField(
            model_name='menutheme',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='menu_questions', through='quiz.MenuThemeQuestion', to='quiz.question'),
        ),
        migrations.CreateModel(
            name='DeadlyBurgerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('deadly_burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.deadlyburger')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('deadly_burger', 'question')},
            },
        ),
        migrations.AddField(
            model_name='deadlyburger',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='deadly_burgers', through='quiz.DeadlyBurgerQuestion', to='quiz.question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('addition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.addition')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('addition', 'question')},
            },
        ),
        migrations.AddField(
            model_name='addition',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='addition_questions', through='quiz.AdditionQuestion', to='quiz.question'),
        ),
        migrations.CreateModel(
            name='BurgerQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('toss', models.TextField()),
                ('addition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.addition')),
                ('deadly_burger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.deadlyburger')),
                ('menus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burger_quiz', to='quiz.menus')),
                ('nuggets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.nuggets')),
                ('salt_or_pepper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.saltorpepper')),
            ],
            options={
                'verbose_name_plural': 'Burger Quiz',
            },
        ),
        migrations.CreateModel(
            name='SaltOrPepperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('salt_or_pepper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.saltorpepper')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('salt_or_pepper', 'question')},
            },
        ),
        migrations.AddField(
            model_name='saltorpepper',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='salt_or_pepper_questions', through='quiz.SaltOrPepperQuestion', to='quiz.question'),
        ),
    ]
