# Generated by Django 5.2.6 on 2026-02-18 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burgerquiz',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Burger Quiz'},
        ),
        migrations.AddField(
            model_name='addition',
            name='original',
            field=models.BooleanField(default=False, help_text="True = manche issue d'une émission diffusée."),
        ),
        migrations.AddField(
            model_name='burgerquiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='burgerquiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deadlyburger',
            name='original',
            field=models.BooleanField(default=False, help_text="True = manche issue d'une émission diffusée."),
        ),
        migrations.AddField(
            model_name='menus',
            name='original',
            field=models.BooleanField(default=False, help_text="True = manche issue d'une émission diffusée."),
        ),
        migrations.AddField(
            model_name='nuggets',
            name='original',
            field=models.BooleanField(default=False, help_text="True = manche issue d'une émission diffusée."),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Lien externe vers un audio.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='original',
            field=models.BooleanField(default=False, help_text="True = question issue d'une émission diffusée, False = créée manuellement."),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True, help_text="Lien externe vers une vidéo (ex. extrait d'émission).", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='saltorpepper',
            name='choice_labels',
            field=models.JSONField(default=list, help_text="Liste des propositions (ex. ['Noir', 'Blanc'] ou ['Noir', 'Blanc', 'Les deux']). Entre 2 et 5 libellés."),
        ),
        migrations.AddField(
            model_name='saltorpepper',
            name='original',
            field=models.BooleanField(default=False, help_text="True = manche issue d'une émission diffusée."),
        ),
        migrations.AddConstraint(
            model_name='additionquestion',
            constraint=models.UniqueConstraint(fields=('question',), name='unique_question_addition'),
        ),
        migrations.AddConstraint(
            model_name='menuthemequestion',
            constraint=models.UniqueConstraint(fields=('question',), name='unique_question_menu_theme'),
        ),
        migrations.AddConstraint(
            model_name='saltorpepperquestion',
            constraint=models.UniqueConstraint(fields=('question',), name='unique_question_salt_or_pepper'),
        ),
    ]
