# Generated by Django 6.0.2 on 2026-02-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='original',
            field=models.BooleanField(default=False, help_text="True = manche issue d'une émission diffusée."),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, help_text='Lien externe vers une image.', max_length=500, null=True),
        ),
    ]
