# Generated by Django 6.0.2 on 2026-02-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_addition_original_alter_question_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutheme',
            name='original',
            field=models.BooleanField(default=True, help_text="True = thème créé directement, False = issue d'une émission diffusée."),
        ),
        migrations.AlterField(
            model_name='addition',
            name='original',
            field=models.BooleanField(default=True, help_text="True = créée directement, False = issue d'une émission diffusée."),
        ),
        migrations.AlterField(
            model_name='deadlyburger',
            name='original',
            field=models.BooleanField(default=True, help_text="True = créée directement, False = issue d'une émission diffusée."),
        ),
        migrations.AlterField(
            model_name='menus',
            name='original',
            field=models.BooleanField(default=True, help_text="True = créée directement, False = issue d'une émission diffusée."),
        ),
        migrations.AlterField(
            model_name='nuggets',
            name='original',
            field=models.BooleanField(default=True, help_text="True = créée directement, False = issue d'une émission diffusée."),
        ),
        migrations.AlterField(
            model_name='question',
            name='original',
            field=models.BooleanField(default=True, help_text="True = créée directement, False = issue d'une émission diffusée."),
        ),
        migrations.AlterField(
            model_name='saltorpepper',
            name='original',
            field=models.BooleanField(default=True, help_text="True = créée directement, False = issue d'une émission diffusée."),
        ),
    ]
