# Generated by Django 6.0.2 on 2026-02-28 11:27

import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_uuid_tagged_item'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInterlude',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('youtube_url', models.URLField(verbose_name='URL YouTube')),
                ('youtube_video_id', models.CharField(blank=True, editable=False, max_length=20, verbose_name='ID vidéo YouTube')),
                ('interlude_type', models.CharField(choices=[('IN', 'Intro'), ('OU', 'Outro'), ('PU', 'Pub'), ('IL', 'Interlude')], default='IL', max_length=2, verbose_name="Type d'interlude")),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (secondes)')),
                ('autoplay', models.BooleanField(default=True, verbose_name='Lecture automatique')),
                ('skip_allowed', models.BooleanField(default=True, verbose_name='Skip autorisé')),
                ('skip_after_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Skip après (secondes)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_authored', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='quiz.UUIDTaggedItem', to='taggit.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Interlude vidéo',
                'verbose_name_plural': 'Interludes vidéo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BurgerQuizElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(verbose_name='Ordre')),
                ('element_type', models.CharField(choices=[('round', 'Manche'), ('interlude', 'Interlude')], max_length=10, verbose_name="Type d'élément")),
                ('round_type', models.CharField(blank=True, choices=[('NU', 'Nuggets'), ('SP', 'Sel ou Poivre'), ('ME', 'Menu'), ('AD', 'Addition'), ('DB', 'Burger de la Mort')], max_length=2, null=True, verbose_name='Type de manche')),
                ('burger_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_elements', to='quiz.burgerquiz', verbose_name='Burger Quiz')),
                ('interlude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='burger_quiz_elements', to='quiz.videointerlude', verbose_name='Interlude')),
            ],
            options={
                'verbose_name': 'Élément de Burger Quiz',
                'verbose_name_plural': 'Éléments de Burger Quiz',
                'ordering': ['burger_quiz', 'order'],
                'unique_together': {('burger_quiz', 'order')},
            },
        ),
    ]
