# Generated by Django 6.0.2 on 2026-04-05 23:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_videointerlude_burgerquizelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burgerquiz',
            name='addition',
        ),
        migrations.RemoveField(
            model_name='burgerquiz',
            name='deadly_burger',
        ),
        migrations.RemoveField(
            model_name='burgerquiz',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='burgerquiz',
            name='nuggets',
        ),
        migrations.RemoveField(
            model_name='burgerquiz',
            name='salt_or_pepper',
        ),
        migrations.RemoveField(
            model_name='burgerquizelement',
            name='round_type',
        ),
        migrations.RemoveField(
            model_name='videointerlude',
            name='interlude_type',
        ),
        migrations.AddField(
            model_name='burgerquizelement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='burgerquizelement',
            name='element_type',
            field=models.CharField(choices=[('round', 'Manche'), ('interlude', 'Interlude vidéo')], max_length=20, verbose_name="Type d'élément"),
        ),
        migrations.AlterField(
            model_name='burgerquizelement',
            name='interlude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structure_usages', to='quiz.videointerlude', verbose_name='Interlude vidéo'),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_type', models.CharField(choices=[('nuggets', 'Nuggets'), ('salt_or_pepper', 'Sel ou Poivre'), ('addition', 'Addition'), ('deadly_burger', 'Burger de la Mort'), ('menus', 'Menus')], max_length=32, verbose_name='type de manche')),
                ('addition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_entry', to='quiz.addition')),
                ('deadly_burger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_entry', to='quiz.deadlyburger')),
                ('menus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_entry', to='quiz.menus')),
                ('nuggets', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_entry', to='quiz.nuggets')),
                ('salt_or_pepper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_entry', to='quiz.saltorpepper')),
            ],
            options={
                'verbose_name': 'Manche (registre)',
                'verbose_name_plural': 'Manches (registre)',
            },
        ),
        migrations.AddField(
            model_name='burgerquizelement',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structure_usages', to='quiz.round', verbose_name='Manche (registre)'),
        ),
    ]
