# Generated by Django 6.0.2 on 2026-04-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_burgerquiz_addition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('NU', 'Nuggets'), ('SP', 'Sel ou Poivre'), ('ME', 'Menus'), ('AD', 'Addition'), ('DB', 'Burger de la Mort')], max_length=2),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_type',
            field=models.CharField(choices=[('nuggets', 'Nuggets'), ('salt_or_pepper', 'Sel ou Poivre'), ('menus', 'Menus'), ('addition', 'Addition'), ('deadly_burger', 'Burger de la Mort')], max_length=32, verbose_name='type de manche'),
        ),
    ]
