# Generated by Django 6.0.2 on 2026-04-05 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('pk',), 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
